name: Release - CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
    types:
      - manual-trigger

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.8.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn build-lib
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
